In [41]:
import pandas as pd
import numpy as np
import matplotlib
import os
import matplotlib.pyplot as plt
import glob
import pandas as pd

# DSADS Dataset

In [ ]:
path = r'data/DSADS/'
all_files = glob.glob(path + "/*.csv")

lst = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    lst.append(df)

df = pd.concat(lst, axis=0, ignore_index=True)

In [ ]:
label_mapping = {1: 'Sitting',
              2: 'Standing',
              3: 'Lying on back',
              4: 'On right side',
              5: 'Ascending stairs',
              6: 'Descending stairs',
              7: 'Standing in an elevator still',
              8: 'Moving around in an elevator',
              9:  'Walking in a parking lot',
              10: 'Walking on a treadmill flat',
              11: 'Walking on a treadmill 15 deg',
              12: 'Running on a treadmill',
              13: 'Exercising on a stepper',
              14: 'Exercising on a cross trainer',
              15: 'Cycling on an exercise bike in horizontal',
              16: 'Cycling on an exercise bike in vertical positions',
              17: 'Rowing',
              18: 'Jumping',
              19: 'Playing basketball'}

# Convert numerical labels to categorical names
df['Label']= [label_mapping[label] for label in df['Label']]

In [ ]:
df.to_csv('data/DSADS/All_dataset.csv')

# PAMAP2 Dataset

In [89]:
#https://github.com/andreasKyratzis/PAMAP2-Physical-Activity-Monitoring-Data-Analysis-and-ML/blob/master/pamap2.ipynb
# Load data
list_of_files = ['../data/PAMAP2_Dataset/subject104.dat']
                 #'data/PAMAP2_Dataset/subject102.dat',
                 #'data/PAMAP2_Dataset/subject103.dat',
                 #'data/PAMAP2_Dataset/subject104.dat',
                 #'data/PAMAP2_Dataset/subject105.dat',
                 #'data/PAMAP2_Dataset/subject106.dat',
                 #'data/PAMAP2_Dataset/subject107.dat',
                 #'data/PAMAP2_Dataset/subject108.dat',
                 #'data/PAMAP2_Dataset/subject109.dat' ]

subjectID = [1,2,3,4,5,6,7,8,9]

activityIDdict = {0: 'transient',
              1: 'lying',
              2: 'sitting',
              3: 'standing',
              4: 'walking',
              5: 'running',
              6: 'cycling',
              7: 'Nordic_walking',
              9: 'watching_TV',
              10: 'computer_work',
              11: 'car driving',
              12: 'ascending_stairs',
              13: 'descending_stairs',
              16: 'vacuum_cleaning',
              17: 'ironing',
              18: 'folding_laundry',
              19: 'house_cleaning',
              20: 'playing_soccer',
              24: 'rope_jumping' }

colNames = ["timestamp", "activityID","heartrate"]

IMUhand = ['handTemperature', 
           'handAcc16_1', 'handAcc16_2', 'handAcc16_3', 
           'handAcc6_1', 'handAcc6_2', 'handAcc6_3', 
           'handGyro1', 'handGyro2', 'handGyro3', 
           'handMagne1', 'handMagne2', 'handMagne3',
           'handOrientation1', 'handOrientation2', 'handOrientation3', 'handOrientation4']

IMUchest = ['chestTemperature', 
           'chestAcc16_1', 'chestAcc16_2', 'chestAcc16_3', 
           'chestAcc6_1', 'chestAcc6_2', 'chestAcc6_3', 
           'chestGyro1', 'chestGyro2', 'chestGyro3', 
           'chestMagne1', 'chestMagne2', 'chestMagne3',
           'chestOrientation1', 'chestOrientation2', 'chestOrientation3', 'chestOrientation4']

IMUankle = ['ankleTemperature', 
           'ankleAcc16_1', 'ankleAcc16_2', 'ankleAcc16_3', 
           'ankleAcc6_1', 'ankleAcc6_2', 'ankleAcc6_3', 
           'ankleGyro1', 'ankleGyro2', 'ankleGyro3', 
           'ankleMagne1', 'ankleMagne2', 'ankleMagne3',
           'ankleOrientation1', 'ankleOrientation2', 'ankleOrientation3', 'ankleOrientation4']

columns = colNames + IMUhand + IMUchest + IMUankle  #all columns in one list

len(columns)

54

In [90]:
dataCollection = pd.DataFrame()
for file in list_of_files:
    procData = pd.read_table(file, header=None, sep='\s+')
    procData.columns = columns
    procData['subject_id'] = int(file[-5])
    dataCollection = dataCollection.append(procData, ignore_index=True)

dataCollection.reset_index(drop=True, inplace=True)
dataCollection.head()

,timestamp,activityID,heartrate,handTemperature,handAcc16_1,handAcc16_2,handAcc16_3,handAcc6_1,handAcc6_2,handAcc6_3,...,ankleGyro2,ankleGyro3,ankleMagne1,ankleMagne2,ankleMagne3,ankleOrientation1,ankleOrientation2,ankleOrientation3,ankleOrientation4,subject_id
0,5.71,0,NaN,31.75,-1.54309,5.78581,7.73342,-1.58707,5.77449,7.89554,...,-0.033188,0.018301,-46.7519,19.7154,9.44721,0.420604,0.506287,0.601928,0.452159,4
1,5.72,0,NaN,31.75,-1.69986,5.55834,7.61638,-1.57213,5.75928,7.89556,...,0.036956,-0.014232,-46.5148,20.3460,9.02181,0.424410,0.504851,0.601741,0.450455,4
2,5.73,0,NaN,31.75,-1.54603,5.55784,7.69566,-1.57276,5.72904,7.85033,...,0.022195,0.010928,-46.4840,19.1874,9.59060,0.421472,0.506134,0.601398,0.452228,4
3,5.74,0,NaN,31.75,-1.57954,5.59708,7.81049,-1.51222,5.75881,7.85020,...,-0.004018,-0.026358,-47.5172,19.6244,9.30279,0.421292,0.506310,0.599558,0.454636,4
4,5.75,0,NaN,31.75,-1.51225,5.55654,7.58071,-1.46764,5.72824,7.80492,...,-0.041724,-0.006069,-47.5133,19.8842,10.15350,0.419774,0.508406,0.597869,0.455923,4

In [91]:
df = dataCollection.drop(['subject_id','timestamp', 'handTemperature','heartrate', 'handOrientation1', 'handOrientation2', 'handOrientation3', 'handOrientation4',
                    'chestTemperature','ankleOrientation1', 'ankleOrientation2', 'ankleOrientation3', 'ankleOrientation4',
                    'ankleTemperature', 'ankleOrientation1', 'ankleOrientation2', 'ankleOrientation3', 'ankleOrientation4'], axis=1)

In [92]:
label_mapping = {0: 'Transient',
              1: 'Lying',
              2: 'Sitting',
              3: 'Standing',
              4: 'Walking',
              5: 'Running',
              6: 'Cycling',
              7: 'Nordic walking',
              9: 'Watching TV',
              10: 'Computer work',
              11: 'Car driving',
              12: 'Ascending stairs',
              13: 'Descending stairs',
              16: 'Vacuum cleaning',
              17: 'Ironing',
              18: 'Folding laundry',
              19: 'House cleaning',
              20: 'Playing soccer',
              24: 'Rope jumping' }

# Convert numerical labels to categorical names
df['activityID']= [label_mapping[label] for label in df['activityID']]

In [93]:
df['activityID'].value_counts()

Transient            98155
Walking              31932
Nordic walking       27533
Sitting              25492
Ironing              24995
Standing             24706
Lying                23047
Cycling              22699
Vacuum cleaning      20037
Ascending stairs     16694
Descending stairs    14285
Running                  1
Name: activityID, dtype: int64

In [94]:
value_to_drop = 'Transient'
filtered_df = df[df['activityID']!= value_to_drop]

In [95]:
filtered_df['activityID'].value_counts()

Walking              31932
Nordic walking       27533
Sitting              25492
Ironing              24995
Standing             24706
Lying                23047
Cycling              22699
Vacuum cleaning      20037
Ascending stairs     16694
Descending stairs    14285
Running                  1
Name: activityID, dtype: int64

In [96]:
filtered_df.to_csv('../data/PAMAP2_Dataset/Subjects_104.csv') 
#filtered_df.to_csv('data/PAMAP2_Dataset/All_dataset.csv')

# Preprocessing

In [162]:
#df = pd.read_csv('../data/DSADS/Player_03.csv')
df = pd.read_csv('../data/PAMAP2_Dataset/Subjects_104.csv')

In [163]:
df.shape

(231421, 42)

In [164]:
df.head(5)

,Unnamed: 0,activityID,handAcc16_1,handAcc16_2,handAcc16_3,handAcc6_1,handAcc6_2,handAcc6_3,handGyro1,handGyro2,...,ankleAcc16_3,ankleAcc6_1,ankleAcc6_2,ankleAcc6_3,ankleGyro1,ankleGyro2,ankleGyro3,ankleMagne1,ankleMagne2,ankleMagne3
0,6954,Lying,-8.66987,3.18279,3.17092,-8.59520,3.28351,3.19673,0.052647,-0.019979,...,-2.28195,9.47316,1.67818,-1.95422,0.015683,0.024698,0.006216,-45.5333,-56.3413,-2.79967
1,6955,Lying,-8.66479,3.33555,3.28594,-8.58000,3.28341,3.21182,0.032087,0.004228,...,-2.39783,9.48831,1.64797,-1.92394,0.030197,-0.027046,0.003406,-46.3114,-56.0466,-3.37008
2,6956,Lying,-8.63663,3.29497,3.01709,-8.54948,3.25306,3.28736,0.061452,0.006872,...,-2.20474,9.51791,1.66297,-2.03009,-0.002765,0.006748,0.013089,-46.8207,-56.0208,-3.23007
3,6957,Lying,-8.52192,3.10507,3.09642,-8.53416,3.26806,3.30241,0.046607,-0.006672,...,-2.35877,9.53345,1.70850,-1.90924,-0.000144,0.009778,0.002096,-46.1712,-56.5682,-3.22715
4,6958,Lying,-8.52085,3.25683,3.09592,-8.51909,3.26795,3.30239,0.037953,-0.026937,...,-2.32062,9.53355,1.61779,-1.87867,0.029180,-0.005140,-0.002693,-47.0789,-55.8792,-3.23114

In [165]:
#df = df.drop(columns=df.columns[0], axis=1)

In [166]:
df.head(5)

,Unnamed: 0,activityID,handAcc16_1,handAcc16_2,handAcc16_3,handAcc6_1,handAcc6_2,handAcc6_3,handGyro1,handGyro2,...,ankleAcc16_3,ankleAcc6_1,ankleAcc6_2,ankleAcc6_3,ankleGyro1,ankleGyro2,ankleGyro3,ankleMagne1,ankleMagne2,ankleMagne3
0,6954,Lying,-8.66987,3.18279,3.17092,-8.59520,3.28351,3.19673,0.052647,-0.019979,...,-2.28195,9.47316,1.67818,-1.95422,0.015683,0.024698,0.006216,-45.5333,-56.3413,-2.79967
1,6955,Lying,-8.66479,3.33555,3.28594,-8.58000,3.28341,3.21182,0.032087,0.004228,...,-2.39783,9.48831,1.64797,-1.92394,0.030197,-0.027046,0.003406,-46.3114,-56.0466,-3.37008
2,6956,Lying,-8.63663,3.29497,3.01709,-8.54948,3.25306,3.28736,0.061452,0.006872,...,-2.20474,9.51791,1.66297,-2.03009,-0.002765,0.006748,0.013089,-46.8207,-56.0208,-3.23007
3,6957,Lying,-8.52192,3.10507,3.09642,-8.53416,3.26806,3.30241,0.046607,-0.006672,...,-2.35877,9.53345,1.70850,-1.90924,-0.000144,0.009778,0.002096,-46.1712,-56.5682,-3.22715
4,6958,Lying,-8.52085,3.25683,3.09592,-8.51909,3.26795,3.30239,0.037953,-0.026937,...,-2.32062,9.53355,1.61779,-1.87867,0.029180,-0.005140,-0.002693,-47.0789,-55.8792,-3.23114

In [167]:
X = df.drop(['activityID'], axis=1)
Y = df['activityID']

In [168]:
def windows(series,window_size,overlap):
    start = 0
    while start+window_size <= series.shape[0]:
        yield int(start), int(start + window_size)
        start += window_size - overlap
        
        
def segment_signal(series,window_size,overlap):
    windowed_series = np.array([])
    for k in range(series.shape[1]):
        print("Windowing Column %d"%(k))
        temp_series = np.array([])
        for (start, end) in windows(series,window_size,overlap):
            if start==0:
                temp_series = series[start:end,k].T
            else:
                temp_series = np.vstack([temp_series,series[start:end,k].T])
        if k==0:
            windowed_series = temp_series
        else:
            windowed_series = np.vstack([windowed_series,temp_series])
    windowed_series = windowed_series.reshape((k+1,int(windowed_series.shape[0]/(k+1)),window_size))
    return windowed_series

def segment_Activity_Label(label_series,window_size,overlap):
    windowed_labels = np.array([])
    for (start, end) in windows(label_series,window_size,overlap):

        if start==0:
            windowed_labels = max(label_series[start:end])[0]
        else:
            windowed_labels = np.vstack([windowed_labels,max(label_series[start:end])[0]])
    return windowed_labels

In [169]:
window_size = 100


overlap = 50

In [170]:
Features = X
Activity_Label = Y

In [171]:
X_full_appended_temp = np.asarray(Features)
X_full_appended = segment_signal(X_full_appended_temp,window_size,overlap)
X_full_appended = X_full_appended.reshape(X_full_appended.shape[1],X_full_appended.shape[0],X_full_appended.shape[2])

Activity_Label_full_temp = np.asarray(Activity_Label)
Activity_Label_full_temp = np.squeeze(np.ndarray.tolist(Activity_Label_full_temp))
Activity_Label_full_temp = Activity_Label_full_temp.reshape(len(Activity_Label_full_temp),1)
Activity_Label_full = segment_Activity_Label(Activity_Label_full_temp,window_size,overlap)

Windowing Column 0
Windowing Column 1
Windowing Column 2
Windowing Column 3
Windowing Column 4
Windowing Column 5
Windowing Column 6
Windowing Column 7
Windowing Column 8
Windowing Column 9
Windowing Column 10
Windowing Column 11
Windowing Column 12
Windowing Column 13
Windowing Column 14
Windowing Column 15
Windowing Column 16
Windowing Column 17
Windowing Column 18
Windowing Column 19
Windowing Column 20
Windowing Column 21
Windowing Column 22
Windowing Column 23
Windowing Column 24
Windowing Column 25
Windowing Column 26
Windowing Column 27
Windowing Column 28
Windowing Column 29
Windowing Column 30
Windowing Column 31
Windowing Column 32
Windowing Column 33
Windowing Column 34
Windowing Column 35
Windowing Column 36
Windowing Column 37
Windowing Column 38
Windowing Column 39
Windowing Column 40

In [172]:
X_full_appended.shape

(4627, 41, 100)

In [173]:
Activity_Label_full.shape

(4627, 1)

In [174]:
X = X_full_appended.reshape(X_full_appended.shape[0], X_full_appended.shape[2], X_full_appended.shape[1])

In [175]:
X.shape

(4627, 100, 41)

In [176]:
Activity_Label_full

array([['Lying'],
       ['Lying'],
       ['Lying'],
       ...,
       ['Cycling'],
       ['Cycling'],
       ['Cycling']], dtype='<U17')

In [177]:
unique, counts = np.unique(Activity_Label_full, return_counts=True)
print(unique, counts)

['Ascending stairs' 'Cycling' 'Descending stairs' 'Ironing' 'Lying'
 'Nordic walking' 'Sitting' 'Standing' 'Vacuum cleaning' 'Walking'] [330 452 288 498 459 551 510 496 403 640]

In [178]:
np.save("../data/PAMAP2_Dataset/Subjects_104_data",X)
#np.save("../data/DSADS/DSADS_03_Player_data",X)

In [179]:
#np.save("../data/DSADS/DSADS_03_Player_labels",Activity_Label_full)
np.save("../data/PAMAP2_Dataset/Subjects_104_labels",Activity_Label_full)